#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
#
Name     : pypi-ruamel.yaml.clib
Version  : 0.2.7
Release  : 33
URL      : https://files.pythonhosted.org/packages/d5/31/a3e6411947eb7a4f1c669f887e9e47d61a68f9d117f10c3c620296694a0b/ruamel.yaml.clib-0.2.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/d5/31/a3e6411947eb7a4f1c669f887e9e47d61a68f9d117f10c3c620296694a0b/ruamel.yaml.clib-0.2.7.tar.gz
Summary  : C version of reader, parser and emitter for ruamel.yaml derived from libyaml
Group    : Development/Tools
License  : MIT
Requires: pypi-ruamel.yaml.clib-license = %{version}-%{release}
Requires: pypi-ruamel.yaml.clib-python = %{version}-%{release}
Requires: pypi-ruamel.yaml.clib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : python3-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
ruamel.yaml.clib
================
``ruamel.yaml.clib`` is the C based reader/scanner and emitter for ruamel.yaml

%package license
Summary: license components for the pypi-ruamel.yaml.clib package.
Group: Default

%description license
license components for the pypi-ruamel.yaml.clib package.


%package python
Summary: python components for the pypi-ruamel.yaml.clib package.
Group: Default
Requires: pypi-ruamel.yaml.clib-python3 = %{version}-%{release}

%description python
python components for the pypi-ruamel.yaml.clib package.


%package python3
Summary: python3 components for the pypi-ruamel.yaml.clib package.
Group: Default
Requires: python3-core
Provides: pypi(ruamel.yaml.clib)

%description python3
python3 components for the pypi-ruamel.yaml.clib package.


%prep
%setup -q -n ruamel.yaml.clib-0.2.7
cd %{_builddir}/ruamel.yaml.clib-0.2.7
pushd ..
cp -a ruamel.yaml.clib-0.2.7 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1683047762
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-ruamel.yaml.clib
cp %{_builddir}/ruamel.yaml.clib-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-ruamel.yaml.clib/0dc44932c3fc39784e80749bc314539181238dd8 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-ruamel.yaml.clib/0dc44932c3fc39784e80749bc314539181238dd8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
